Added SetsuScans to Madara
Paperback-iOS/extensions-generic pull request #15
Opened 2021-11-21 01:06 UTC by buhbbl

I have fixed a syntax error for the chapter names and added setsuscans to the extension.

2021-11-30 10:16 UTC, TheNetsky requested changes

2021-11-30 10:16 UTC, TheNetsky commented on src/SetsuScans/SetsuScans.ts
> +    override async getMangaDetails(mangaId: string): Promise<Manga> {
Why do you need this override?

2021-11-30 10:16 UTC, TheNetsky commented on src/SetsuScans/SetsuScans.ts
> +    override async getNumericId(mangaId: string): Promise<string> {
Let's not mess with the id's per source, please use generic class. I also don't see a reason why you need this override in the first place. Look at the other Madara sources.

2021-11-30 10:16 UTC, TheNetsky commented on src/SetsuScans/SetsuScansParser.ts
> +    override parseMangaDetails($: CheerioSelector, mangaId: string): Manga {
Why do you need this override, it seems like the exact same as the generic class one.

2021-11-30 10:16 UTC, TheNetsky commented on src/SetsuScans/SetsuScansParser.ts
> +    override parseChapterList($: CheerioSelector, mangaId: string, source: any): Chapter[] {
Same as above, remove it if not needed, if it is needed, place a comment within the code WHY it's needed.

I suggest you take a look at the other Madara sources in this repo and follow their example.

2021-12-03 11:46 UTC, buhbbl commented on src/SetsuScans/SetsuScans.ts
> +    override async getNumericId(mangaId: string): Promise<string> {
The numeric id in setsuscans is encoded in base64 in the src attr instead of being written as a js function.

2021-12-03 11:47 UTC, buhbbl commented on src/SetsuScans/SetsuScansParser.ts
> +    override parseMangaDetails($: CheerioSelector, mangaId: string): Manga {
This function has a different way of grabbing the numeric id. As mentioned before, the numeric id in setsuscans is encoded in base64 in the src attr instead of being written as a js function.

2021-12-03 11:54 UTC, buhbbl commented on src/SetsuScans/SetsuScans.ts
> +    override async getMangaDetails(mangaId: string): Promise<Manga> {
Removed in the new commit

2021-12-03 11:54 UTC, buhbbl commented on src/SetsuScans/SetsuScansParser.ts
> +    override parseChapterList($: CheerioSelector, mangaId: string, source: any): Chapter[] {
Removed in the new commit

2021-12-21 11:07 UTC, TheNetsky commented
I'm not sure how viable this source is going to be since more than 70% of their manga is redirecting to biliblicomics. So this will cause a lot of annoyance for users and for support. So for now I'm not going to approve this PR.

2021-12-24 13:24 UTC, closed without merging