Nepnep
Paperback-iOS/extensions-generic pull request #6
Opened 2021-09-17 15:43 UTC by GameFuzzy

Nepnep

2021-09-17 18:02 UTC, TheNetsky submitted a review, later dismissed
Looks decent for something by Fuzzy's standards

2021-09-17 18:25 UTC, nar1n approved these changes

2021-09-17 18:49 UTC, FramboisePi commented on package.json
>    "version": "1.0.0",
Would you mind adding a `repositoryName` name field?
Something like:
```
"repositoryName": "Extensions NepNep",
```

2021-09-17 18:50 UTC, FramboisePi requested changes
Hum are you sure about the base branch? I think it should be `NepNep`

2021-09-17 19:44 UTC, FramboisePi approved these changes
Trying to approve this pull request

2021-09-17 20:02 UTC, FramboisePi approved these changes
Trying to approve this pull request

2021-09-18 09:31 UTC, TheNetsky approved these changes
If this doesn't work, Paper didn't fix shit

2021-09-18 09:33 UTC, merged